[frontend]
frontend.somaraju.online

[local]
localhost

[mongodb]
mongodb.somaraju.online

[catalogue]
catalogue.somaraju.online

[redis]
redis.somaraju.online

[user]
user.somaraju.online

[cart]
cart.somaraju.online

[mysql]
mysql.somaraju.online

[shipping]
shipping.somaraju.online



